jobs:
- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_stable'
    vmImage: 'macOS-latest'
    toolchain: 'stable'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_beta'
    vmImage: 'macOS-latest'
    toolchain: 'beta'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'macOS-latest'
    toolchain: 'nightly'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_1_34_1'
    vmImage: 'macOS-latest'
    toolchain: '1.34.1'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_stable'
    vmImage: 'ubuntu-latest'
    toolchain: 'stable'

- template: 'azure-template-windows.yml'
  parameters:
    name: 'Windows_default_features'
    vmImage: 'windows-latest'
    toolchain: 'stable'
