name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
          - beta
          - nightly
          - macOS
          - Windows

        include:
          - name: beta
            toolchain: beta
          - name: nightly
            toolchain: nightly
          - name: macOS
            os: macOS-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain || 'stable' }}
          profile: minimal
          override: true

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update

      - name: Setup cache
        if: runner.os != 'macOS'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-test-${{ steps.tc.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Build "blocking" Feature
        run: cargo build --no-default-features --features "blocking"

      - name: Build "parallel" Feature
        run: cargo build --no-default-features --features "parallel"

      - name: Build "async" Feature
        run: cargo build --no-default-features --features "async"

      - name: Build Default Features
        run: cargo build

      - name: Test All Features
      # TODO: Skeptic fails testing the README.md on 'nightly' for an unknown reason.
        if: ${{ matrix.toolchain != 'nightly' }}
        run: |
          cargo test --all-features
